---
title: "figure_4"
format: pdf
editor_options: 
  chunk_output_type: console
---
```{r}
#| message: false
#| echo: false
library(tidyverse)
library(repeatData)
library(gt)
library(lme4)
library(emmeans)
library(pbkrtest)
library(gtsummary)
library(patchwork)
library(reporter)
library(jtools)




```



```{r}
#| message: false
#| echo: false
#| warning: false




# Including only participants with both pre and post tests
filtered_hb.data <- hb.data %>%
  group_by(id) %>%
  filter(n_distinct(timepoint) == 2) %>%
  ungroup()



# Specify the order of the timepoints
filtered_hb.data$timepoint <- factor(filtered_hb.data$timepoint, levels = c("pre", "post"))



# Create the plot for haemoglobin mass
hb <- ggplot(filtered_hb.data, aes(x = timepoint, y = hbmass, fill = timepoint)) +
  # Bar plot for averages
  stat_summary(fun = "mean", geom = "col", fill = c("grey", "grey50")) +
  
  # Individual points and lines
  geom_point() +
  geom_line(aes(group = id), size = 0.1) +
  

  
  # Customize the appearance
  theme_minimal() +
  labs(title = "Hbmass",
       x = NULL,
       y = NULL) +
  theme(
     panel.grid.major = element_blank(),  # Remove major grid lines
    panel.grid.minor = element_blank(),  # Remove minor grid lines
    axis.line = element_line(color = "black"),  # Set axis lines to black
    axis.text = element_text(size = 12),  # Increase axis text size
    axis.title = element_text(size = 14, face = "bold"),  # Increase axis title size and make it bold
    axis.ticks = element_line(color = "black", size = 0.5),  # Add ticks on the axis
    legend.position = "bottom"  # Move legend to the bottom
  ) +
  scale_y_continuous(breaks = seq(0,1250, 250)) +
  guides(fill = FALSE) # Remove the legend for fill
  

# Create the plot blood volume
bv <- ggplot(filtered_hb.data, aes(x = timepoint, y = bv, fill = timepoint)) +
  # Bar plot for averages
  stat_summary(fun = "mean", geom = "col", fill = c("grey", "grey50")) +
  
  # Individual points and lines
  geom_point() +
  geom_line(aes(group = id), size = 0.1) +
  
  
  # Customize the appearance
  theme_minimal() +
  labs(title = "blood volume",
       x = NULL,
       y = NULL) +
    theme(
     panel.grid.major = element_blank(),  # Remove major grid lines
    panel.grid.minor = element_blank(),  # Remove minor grid lines
    axis.line = element_line(color = "black"),  # Set axis lines to black
    axis.text = element_text(size = 12),  # Increase axis text size
    axis.title = element_text(size = 14, face = "bold"),  # Increase axis title size and make it bold
    axis.ticks = element_line(color = "black", size = 0.5),  # Add ticks on the axis
    legend.position = "bottom"  # Move legend to the bottom
  ) +
  scale_y_continuous(breaks = seq(0,8000, 1000)) +
  guides(fill = FALSE) # Remove the legend for fill


# Create the plot for red blood cell volume
rbcv <- ggplot(filtered_hb.data, aes(x = timepoint, y = rbcv, fill = timepoint)) +
  # Bar plot for averages
  stat_summary(fun = "mean", geom = "col", fill = c("grey", "grey50")) +
  
  # Individual points and lines
  geom_point() +
  geom_line(aes(group = id), size = 0.1) +
  
  
  # Customize the appearance
  theme_minimal() +
  labs(title = "red blood cell volume",
       x = NULL,
       y = NULL) +
    theme(
     panel.grid.major = element_blank(),  # Remove major grid lines
    panel.grid.minor = element_blank(),  # Remove minor grid lines
    axis.line = element_line(color = "black"),  # Set axis lines to black
    axis.text = element_text(size = 12),  # Increase axis text size
    axis.title = element_text(size = 14, face = "bold"),  # Increase axis title size and make it bold
    axis.ticks = element_line(color = "black", size = 0.5),  # Add ticks on the axis
    legend.position = "bottom"  # Move legend to the bottom
  ) +
  scale_y_continuous(breaks = seq(0,8000, 1000)) +
  guides(fill = FALSE) # Remove the legend for fill





# Create the plot plasma volume
pv <- ggplot(filtered_hb.data, aes(x = timepoint, y = pv, fill = timepoint)) +
  # Bar plot for averages
  stat_summary(fun = "mean", geom = "col", fill = c("grey", "grey50")) +
  
  # Individual points and lines
  geom_point() +
  geom_line(aes(group = id), size = 0.1) +
  
  
  # Customize the appearance
  theme_minimal() +
  labs(title = "Plasma volume",
       x = NULL,
       y = NULL) +
    theme(
     panel.grid.major = element_blank(),  # Remove major grid lines
    panel.grid.minor = element_blank(),  # Remove minor grid lines
    axis.line = element_line(color = "black"),  # Set axis lines to black
    axis.text = element_text(size = 12),  # Increase axis text size
    axis.title = element_text(size = 14, face = "bold"),  # Increase axis title size and make it bold
    axis.ticks = element_line(color = "black", size = 0.5),  # Add ticks on the axis
    legend.position = "bottom"  # Move legend to the bottom
  ) +
   scale_y_continuous(breaks = seq(0,5000, 1000)) +
  guides(fill = FALSE) # Remove the legend for fill





# Show the combined plots
hb
bv
rbcv
pv

```
